name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Ejecutar prueba
        run: echo "Test exitoso"
